package nstv.design.theme

import androidx.compose.ui.graphics.Color


object SheepColor {
    val Gray = Color(0xFFCCCCCC)
    val Blue = Color(0xFF1976D2)
    val Green = Color(0xFF3DDC84)
    val Black = Color(0xFF191B1B)
    val Purple = Color(0xFF6200EA)
    val Magenta = Color(0xFFC51162)
    val Orange = Color(0xFFFF9800)
}

val md_theme_light_primary = Color(0xFF00677e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFb1ecff)
val md_theme_light_onPrimaryContainer = Color(0xFF001f28)
val md_theme_light_secondary = Color(0xFF4b6269)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcfe7f0)
val md_theme_light_onSecondaryContainer = Color(0xFF061e25)
val md_theme_light_tertiary = Color(0xFF595c7e)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFdee0ff)
val md_theme_light_onTertiaryContainer = Color(0xFF151937)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfafcfd)
val md_theme_light_onBackground = Color(0xFF191c1d)
val md_theme_light_surface = Color(0xFFfafcfd)
val md_theme_light_onSurface = Color(0xFF191c1d)
val md_theme_light_surfaceVariant = Color(0xFFdbe4e8)
val md_theme_light_onSurfaceVariant = Color(0xFF40484b)
val md_theme_light_outline = Color(0xFF70797c)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f2)
val md_theme_light_inverseSurface = Color(0xFF2e3132)
val md_theme_light_inversePrimary = Color(0xFF2ad8ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF2ad8ff)
val md_theme_dark_onPrimary = Color(0xFF003542)
val md_theme_dark_primaryContainer = Color(0xFF004e60)
val md_theme_dark_onPrimaryContainer = Color(0xFFb1ecff)
val md_theme_dark_secondary = Color(0xFFb2cad3)
val md_theme_dark_onSecondary = Color(0xFF1d343b)
val md_theme_dark_secondaryContainer = Color(0xFF344a52)
val md_theme_dark_onSecondaryContainer = Color(0xFFcfe7f0)
val md_theme_dark_tertiary = Color(0xFFc1c4eb)
val md_theme_dark_onTertiary = Color(0xFF2a2e4d)
val md_theme_dark_tertiaryContainer = Color(0xFF414464)
val md_theme_dark_onTertiaryContainer = Color(0xFFdee0ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1d)
val md_theme_dark_onBackground = Color(0xFFe1e3e4)
val md_theme_dark_surface = Color(0xFF191c1d)
val md_theme_dark_onSurface = Color(0xFFe1e3e4)
val md_theme_dark_surfaceVariant = Color(0xFF40484b)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc8cc)
val md_theme_dark_outline = Color(0xFF899296)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1d)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e4)
val md_theme_dark_inversePrimary = Color(0xFF00677e)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF00d5ff)
val error = Color(0xFFba1b1b)
